apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8nmh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0022-tenant/tkrw-pr712-0075-0022-app/devfile-sample-8nmh@sha256:80bde79f1a6fd7996e03a9cacfa6028ae088c97f49b407bb574dd6304c074dd6
        name: my-nodejs
        resources: {}
status: {}
